{{ $clusterReceiverObserver := fromYaml (include "splunk-otel-collector.clusterReceiverObserver" .) }}
{{- if eq (include "splunk-otel-collector.clusterReceiverObserverEnabled" .) "true" }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "splunk-otel-collector.fullname" . }}-cluster-receiver-observer
  labels:
    {{- include "splunk-otel-collector.commonLabels" . | nindent 4 }}
    app: {{ template "splunk-otel-collector.name" . }}
    component: otel-k8s-cluster-receiver-observer
    chart: {{ template "splunk-otel-collector.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
    app.kubernetes.io/component: otel-k8s-cluster-receiver-observer
  {{- if $clusterReceiverObserver.annotations }}
  annotations:
    {{- toYaml $clusterReceiverObserver.annotations | nindent 4 }}
  {{- end }}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: {{ template "splunk-otel-collector.name" . }}
      component: otel-k8s-cluster-receiver-observer
      release: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app: {{ template "splunk-otel-collector.name" . }}
        component: otel-k8s-cluster-receiver-observer
        release: {{ .Release.Name }}
        {{- if $clusterReceiverObserver.podLabels }}
        {{- toYaml $clusterReceiverObserver.podLabels | nindent 8 }}
        {{- end }}
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap-cluster-receiver-observer.yaml") . | sha256sum }}
        {{- if $clusterReceiverObserver.podAnnotations }}
        {{- toYaml $clusterReceiverObserver.podAnnotations | nindent 8 }}
        {{- end }}
        {{- if .Values.autodetect.istio }}
        sidecar.istio.io/inject: "false"
        {{- end }}
    spec:
      serviceAccountName: {{ template "splunk-otel-collector.serviceAccountName" . }}
      nodeSelector:
        {{- if $clusterReceiverObserver.nodeSelector }}
        {{ toYaml $clusterReceiverObserver.nodeSelector | nindent 8 }}
        {{- else }}
          kubernetes.io/os: {{ .Values.isWindows | ternary "windows" "linux" }}
        {{- end }}
      {{- if $clusterReceiverObserver.tolerations }}
      tolerations:
        {{ toYaml $clusterReceiverObserver.tolerations | nindent 8 }}
      {{- end }}
      {{- if $clusterReceiverObserver.affinity }}
      affinity:
        {{- toYaml $clusterReceiverObserver.affinity | nindent 8 }}
      {{- end }}
      {{- if $clusterReceiverObserver.securityContext }}
      securityContext:
        {{ toYaml $clusterReceiverObserver.securityContext | nindent 8 }}
      {{- end }}
      containers:
      - name: otel-collector
        command:
        {{- if .Values.isWindows }}
        - powershell.exe
        - -command
        - .\otelcol.exe
        - --config=C:\\conf\relay.yaml
        {{- else }}
        - /otelcol
        - --config=/conf/relay.yaml
        {{- end }}
        - --metrics-addr=0.0.0.0:8889
        image: {{ template "splunk-otel-collector.image.otelcol" . }}
        imagePullPolicy: {{ .Values.image.otelcol.pullPolicy }}
        env:
          - name: SPLUNK_MEMORY_TOTAL_MIB
            value: "{{ include "splunk-otel-collector.convertMemToMib" $clusterReceiverObserver.resources.limits.memory }}"
          - name: K8S_NODE_NAME
            valueFrom:
              fieldRef:
                fieldPath: spec.nodeName
          - name: K8S_POD_IP
            valueFrom:
              fieldRef:
                apiVersion: v1
                fieldPath: status.podIP
          - name: K8S_POD_NAME
            valueFrom:
              fieldRef:
                fieldPath: metadata.name
          - name: K8S_POD_UID
            valueFrom:
              fieldRef:
                fieldPath: metadata.uid
          - name: K8S_NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if (eq (include "splunk-otel-collector.splunkO11yEnabled" .) "true") }}
          - name: SPLUNK_OBSERVABILITY_ACCESS_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "splunk-otel-collector.secret" . }}
                key: splunk_observability_access_token
          {{- end }}
          {{- if (eq (include "splunk-otel-collector.splunkPlatformEnabled" .) "true") }}
          - name: SPLUNK_PLATFORM_HEC_TOKEN
            valueFrom:
              secretKeyRef:
                name: {{ include "splunk-otel-collector.secret" . }}
                key: splunk_platform_hec_token
          {{- end }}
          {{- with $clusterReceiverObserver.extraEnvs }}
          {{- . | toYaml | nindent 10 }}
          {{- end }}
        readinessProbe:
          {{- if .Values.readinessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
          {{- end }}
          httpGet:
            path: /
            port: 13133
        livenessProbe:
          {{- if .Values.livenessProbe.initialDelaySeconds }}
          initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
          {{- end }}
          httpGet:
            path: /
            port: 13133
        resources:
          {{- toYaml $clusterReceiverObserver.resources | nindent 10 }}
        volumeMounts:
        - mountPath: {{ .Values.isWindows | ternary "C:\\conf" "/conf" }}
          name: collector-configmap
        {{- if $clusterReceiverObserver.extraVolumeMounts }}
        {{- toYaml $clusterReceiverObserver.extraVolumeMounts | nindent 8 }}
        {{- end }}
      terminationGracePeriodSeconds: {{ $clusterReceiverObserver.terminationGracePeriodSeconds }}
      volumes:
      - name: collector-configmap
        configMap:
          name: {{ template "splunk-otel-collector.fullname" . }}-otel-eks-fargate-cluster-receiver-observer
          items:
            - key: relay
              path: relay.yaml
      {{- if $clusterReceiverObserver.extraVolumes }}
      {{- toYaml $clusterReceiverObserver.extraVolumes | nindent 6 }}
      {{- end }}
      {{- if $clusterReceiverObserver.priorityClassName }}
      priorityClassName: {{ $clusterReceiverObserver.priorityClassName }}
      {{- end }}
{{- end }}
